[project]
name = "winipedia-django"
version = "0.2.14"
description = "A utils package for django"
authors = [
    {name = "Winipedia",email = "win.steveker@gmx.de"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.12"
dynamic = ["dependencies"]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[[tool.poetry.packages]]
include = "winipedia_django"

[tool.poetry.dependencies]
winipedia-utils = "*"
django = "*"

[tool.poetry.group.dev.dependencies]
mypy = "*"
ruff = "*"
pre-commit = "*"
django-stubs = "*"
types-setuptools = "*"
types-tqdm = "*"
pytest-mock = "*"
pytest = "*"
types-pyyaml = "*"
types-defusedxml = "*"
bandit = "*"

[tool.ruff]
exclude = [".*", "**/migrations/*.py"]

[tool.ruff.lint]
select = ["ALL"]
ignore = ["D203", "D213", "COM812", "ANN401"]
fixable = ["ALL"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.mypy]
strict = true
warn_unreachable = true
show_error_codes = true
files = "."

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.bandit]
exclude_dirs = ["experiment.py"]
